<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
?>
<?php if ($block->getShowPart() == 'welcome') : ?>
    <li class="greet welcome nav-item dropdown  d-flex align-items-center ml-2" data-bind="scope: 'customer'">
        <!-- ko if: customer().fullname  -->
        <span class="logged-in nav-link dropdown-toggle">
            <span data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().firstname)"></span>
            <br> Account & Orders
        </span>
        <!-- /ko -->
        <!-- ko ifnot: customer().fullname  -->
        <span class="not-logged-in nav-link dropdown-toggle">
              <span data-bind='html:"<?= $block->escapeHtml($welcomeMessage) ?>"'></span>
              <br> Account & Orders
        </span>
        <?= $block->getBlockHtml('header.additional') ?>
        <!-- /ko -->
        <?= $block->getChildHtml() ?>
    </li>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script>
<?php elseif ($block->getShowPart() == 'other') :?>
    <?= $block->getChildHtml() ?>
<?php endif ?>
