<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('nav-link level-top', 'submenu', $columnsLimit)
?>

<nav class="navigation navbar navbar-expand-md navbar-dark bg-dark p-0" data-action="navigation">
    <ul class="navbar-nav justify-content-around w-100">
        <?= /* @noEscape */ $_menuHtml?>
        <?= $block->getChildHtml() ?>
    </ul>
</nav>
