<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores())>1) : ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <li class="nav-item dropdown  d-flex align-items-center ml-2">
        <a class="nav-link dropdown-toggle store-toggle"
                href="#"
                data-toggle="dropdown"
                id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
                role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span><?= $block->escapeHtml($block->getStoreName()) ?></span>
        </a>
        <div class="dropdown-menu" aria-labelledby="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>">
            <?php foreach ($block->getStores() as $_lang) : ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()) : ?>
                    <a class="dropdown-item" href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                        <?= $block->escapeHtml($_lang->getName()) ?>
                    </a>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </li>
<?php endif; ?>